  // Mock events data
  export const events = [
    {
      id: 1,
      title: "Annual Leadership Conference 2025",
      speaker: "Dr. John Maxwell",
      type: "Conference",
      date: "2025-07-15",
      time: "09:00",
      location: "Lagos Conference Center",
      price: "₦25,000",
      attendees: 250,
      maxAttendees: 500,
      status: "upcoming",
      color: "blue",
      tags: ["Global", "Leadership", "Networking"],
      description: "Join us for an inspiring leadership conference that will transform your ministry approach.",
      image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=200&fit=crop"
    },
    {
      id: 2,
      title: "Youth Revival Night",
      speaker: "Pastor Sarah Johnson",
      type: "Revival",
      date: "2025-06-20",
      time: "18:00",
      location: "Main Auditorium",
      price: "Free",
      attendees: 180,
      maxAttendees: 300,
      status: "upcoming",
      color: "purple",
      tags: ["Annual", "Worship", "Community"],
      description: "A powerful night of worship and revival specifically designed for young people.",
      image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400&h=200&fit=crop"
    },
    {
      id: 3,
      title: "Community Outreach Program",
      speaker: "Pastor Michael Brown",
      type: "Evangelism",
      date: "2025-08-10",
      time: "14:00",
      location: "City Center Plaza",
      price: "₦5,000",
      attendees: 95,
      maxAttendees: 200,
      status: "upcoming",
      color: "green",
      tags: ["Christmas", "Celebration", "Family"],
      description: "Reaching out to our community with love and the gospel message.",
      image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=200&fit=crop"
    },
    {
      id: 4,
      title: "Leadership Training Workshop",
      speaker: "Dr. Patricia Williams",
      type: "Leadership Training",
      date: "2025-05-25",
      time: "10:00",
      location: "Training Hall B",
      price: "₦15,000",
      attendees: 45,
      maxAttendees: 50,
      status: "almost-full",
      color: "orange",
       tags: ["Youth", "Connection", "Growth"],
      description: "Intensive training program for emerging leaders in ministry.",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=200&fit=crop"
    },
        {
      id: 5,
      title: "Global Leadership Summit",
      date: "2025-08-15",
      time: "09:00",
      location: "Main Auditorium",
      type: "Global Event",
      category: "leadership",
      description: "Join leaders from around the world for an inspiring summit focused on transformational leadership in the modern age.",
      image: "/api/placeholder/400/300",
      color: "purple",
      featured: true,
      capacity: 500,
      registered: 347,
      tags: ["Global", "Leadership", "Networking"],
      speaker: "International Speakers",
      price: "Free"
    },
    {
      id: 6,
      title: "Annual Conference 2025",
      date: "2025-09-20",
      time: "08:00",
      location: "Convention Center",
      type: "Conference",
      category: "conference",
      description: "Our biggest event of the year featuring powerful worship, inspiring messages, and life-changing connections.",
      image: "/api/placeholder/400/300",
      color: "blue",
      featured: true,
      capacity: 1200,
      registered: 856,
      tags: ["Annual", "Worship", "Community"],
      speaker: "Pastor John Smith",
      price: "Free"
    },
    {
      id: 7,
      title: "Christmas Celebration",
      date: "2025-12-24",
      time: "19:00",
      location: "Main Sanctuary",
      type: "Holiday Event",
      category: "holiday",
      description: "Celebrate the joy of Christmas with special music, candlelight service, and a message of hope.",
      image: "/api/placeholder/400/300",
      color: "red",
      featured: true,
      capacity: 800,
      registered: 234,
      tags: ["Christmas", "Celebration", "Family"],
      speaker: "Senior Pastor",
      price: "Free"
    },
    {
      id: 8,
      title: "Youth Summit 2025",
      date: "2025-07-10",
      time: "18:00",
      location: "Youth Center",
      type: "Youth Event",
      category: "youth",
      description: "An exciting gathering for young people to connect, learn, and grow together in faith and purpose.",
      image: "/api/placeholder/400/300",
      color: "emerald",
      featured: false,
      capacity: 300,
      registered: 189,
      tags: ["Youth", "Connection", "Growth"],
      speaker: "Youth Pastor Sarah",
      price: "Free"
    }
  ];

  export const colorMap = {
    purple: {
      badge: "from-purple-500 to-purple-600",
      gradient: "from-purple-500 to-purple-700",
      light: "from-purple-50 to-purple-100",
      text: "text-purple-600",
      bg: "bg-purple-100",
      border: "border-purple-200",
      hover: "hover:bg-purple-50"
    },
    blue: {
      badge: "from-blue-500 to-indigo-600", 
      gradient: "from-blue-500 to-blue-700",
      light: "from-blue-50 to-blue-100",
      text: "text-blue-600",
      bg: "bg-blue-100",
      border: "border-blue-200",
      hover: "hover:bg-blue-50"
    },
    emerald: {
      badge: "from-emerald-500 to-teal-600",
      gradient: "from-emerald-500 to-emerald-700",
      light: "from-emerald-50 to-emerald-100",
      text: "text-emerald-600",
      bg: "bg-emerald-100",
      border: "border-emerald-200",
      hover: "hover:bg-emerald-50"
    },
    red: {
      badge: "from-red-500 to-rose-600",
      gradient: "from-red-500 to-red-700",
      light: "from-red-50 to-red-100",
      text: "text-red-600",
      bg: "bg-red-100",
      border: "border-red-200",
      hover: "hover:bg-red-50"
    },
    Orange: {
      badge: "from-orange-500 to-yellow-600",
      gradient: "from-orange-500 to-orange-700",
      light: "from-orange-50 to-orange-100",
      text: "text-orange-600",
      bg: "bg-orange-100",
      border: "border-orange-200",
      hover: "hover:bg-orange-50"
    }
  };
